# -*- coding: utf-8 -*-
"""atvvpandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bXVRlKjP89IjrIWQ1Pi6TKP2ohSGgQE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



data = pd.read_csv("/content/PARARAIO - PARARAIO (1).csv",decimal = ",")

data.head(10)

data["DATE"].unique()

data.info()

dia = data["DATE"] == "24/03/2022"
data[dia]

dia_01  = data["DATE"] == "01/04/2022"
data[dia_01]

dia = data["DATE"] == "13/04/2022"
data[dia]

axis=data[['DATE','TIME','aleta_ceramica','inf_pastilha','inf_resist','intermed_past','intermed_resist','parede_ceramica','sup_pastilha','sup_resist']].plot.line(subplots=True, layout=(15,2), figsize=(20,10))

minimo = data.min()
maximo = data.max()


print(minimo,maximo)

data.info()

data.describe()

colunas = data.columns.values
print(colunas)

data[dia_01]

data[dia_01]["aleta_ceramica"].mean()
plt.plot(data[dia_01]['TIME'], data[dia_01]['aleta_ceramica'], label='aleta_ceramica',color = "red")
plt.axhline(y=data[dia_01]["aleta_ceramica"].mean(), color='black', linestyle='--', label='Média')

plt.show()