# -*- coding: utf-8 -*-
"""datascience_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shAZMqU18XdG6iZ0hTMeNnwJz5U3w2rQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    'ano': [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
            2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019],
    'valor': [10, 12, 15, 20, 22, 25, 28, 30, 32, 35,
              40, 42, 45, 48, 50, 52, 55, 58, 60, 62]
}
df = pd.DataFrame(data)

a = pd.cut( df['ano'],np.arange(df['ano'].min(), df['ano'].max(), 2))

print(df.groupby(a)['valor'].mean())

y =  pd.cut( a['yr_built'],np.arange(a['yr_built'].min(), a['yr_built'].max(), 5))
y_ = a.groupby(a)['price'].mean()

y =  pd.cut( a['yr_built'],np.arange(a['yr_built'].min(), a['yr_built'].max(), 20))
y_ = a.groupby(a)['price'].mean()
plt.scatter(x, y_, label = "Média dos  valores em 20 anos" )
plt.xlabel('anos')
plt.ylabel('Média de Preços')
plt.xticks(rotation='vertical')
plt.legend()
plt.show()
print(tabela)

import pandas as pd

# DataFrame de exemplo
data = {
    'ano': [2003, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2009, 2009,
            2010, 2010, 2011, 2013, 2014, 2015, 2016, 2017, 2018, 2019],
    'valor': [10, 12, 15, 20, 22, 25, 28, 30, 32, 35,
              40, 42, 45, 48, 50, 52, 55, 58, 60, 62]
}
df = pd.DataFrame(data)

# Adicionando uma coluna 'intervalo'
df['intervalo'] = pd.cut(df['ano'], bins=range(df['ano'].min(), df['ano'].max() + 6, 5),
                         labels=[f"{i}-{i+4}" for i in range(df['ano'].min(), df['ano'].max(), 5)], right=False)

# Agrupando os dados e calculando a média para cada intervalo
resultado = df.groupby('intervalo')['valor'].mean().reset_index()

# Mostrando os intervalos de 5 anos com as médias correspondentes
for index, row in resultado.iterrows():
    intervalo = row['intervalo']
    media = row['valor']

    print(f"Intervalo: {intervalo}")
    print(f"Média dos Valores: {media}")
    print("="*50)